#!/bin/bash -l
#SBATCH --time=00:10:00
#SBATCH --tasks=6
#SBATCH --mem=1g
#SBATCH --job-name=pspg_tests
#SBATCH --mail-type=ALL
#SBATCH --mail-user=chawl029@umn.edu 
#SBATCH --gres=gpu:k40:1
#SBATCH -p k40
#SBATCH --account=morsedc

module load intel
module load impi

cd $SLURM_SUBMIT_DIR
./Test > log
