#ifndef PSCF_ENVIRONMENT_H
#define PSCF_ENVIRONMENT_H

/*
* PSCF - Polymer Self-Consistent Field Theory
*
* Copyright 2015 - 2025, The Regents of the University of Minnesota
* Distributed under the terms of the GNU General Public License.
*/

#include <util/param/ParamComposite.h>    // base class
#include <pscf/sweep/ParameterModifier.h> // base class

namespace Pscf {

   using namespace Util;

   /**
   * Template for classes that internally generate masks and external fields.
   * 
   * An "environment" in PSCF is defined to be a set of user-defined, 
   * externally imposed fields that affect the resulting SCFT solution.
   * This includes masks and external potential fields. Masks define an
   * inhomogeneous density constraint, where certain regions of the 
   * calculation box may have reduced or zero polymer density. External
   * potential fields define inhomogeneous energetic penalties for 
   * monomer species to be located at certain positions, which are 
   * separate from the saddle-point 'w' potential fields generated by
   * the surrounding species. 
   * 
   * Environment classes (subclasses of Environment) are created
   * through the inclusion of an optional, polymorphic Environment 
   * block of the parameter file. Different combinations of masks and
   * external fields (i.e., different types of environments) will have
   * different class names and different required parameters to define
   * the imposed fields. If an Environment block is included in a 
   * parameter file, the Environment class will read the necessary 
   * parameters, construct imposed fields, and update them as needed.
   * 
   * Imposed fields, in general, are dependent on the size of the 
   * calculation box. If the fields deform non-affinely upon changing
   * the box size, then the imposed fields will also contribute to the
   * stress. Therefore, Environment classes have a stress() method that
   * returns the Environment's contribution to the stress. 
   * 
   * Furthermore, it may be preferable with certain imposed fields to 
   * minimize a property other than fHelmholtz with respect to the 
   * lattice parameters. For instance, in a thin film it is useful to 
   * minimize the excess free energy per unit area, 
   *     (fHelmholtz - fRef) * Delta, 
   * where fRef is a reference free energy and Delta is the film 
   * thickness. To minimize alternative free-energetic properties,
   * one must use an alternate form of the stress. Environment classes
   * provide a method called modifyStress() to convert the stress into
   * this alternate form, which will vary depending on the type of
   * Environment.
   * 
   * \ingroup Pscf_Environment_Module
   */
   class Environment : public ParamComposite, public ParameterModifier
   {

   public:

      /**
      * Constructor.
      */
      Environment();

      /**
      * Destructor.
      */
      ~Environment();

      /**
      * Allocate, check compatibility, calculate, and store the field(s).
      */
      virtual void setEnvironment() = 0;

      /**
      * Check whether system has changed, update the field(s) if necessary.
      */
      virtual void update() = 0;

      /**
      * Return the Environment's contribution to the stress.
      * 
      * This method will only be called when the Environment is used
      * in combination with a variable unit cell. Subclasses can thus
      * leave the method unimplemented if they will only be used in
      * rigid cells. 
      * 
      * \param paramId  index of the lattice parameter with this stress
      */
      virtual double stress(int paramId) const;

      /**
      * Modify stress to minimize a property other than fHelmholtz. 
      * 
      * The property that should be minimized will vary depending on the
      * type of Environment. In cases where fHelmholtz is the desired 
      * property to be minimized, this method returns the stress that
      * it was provided, without modification. This is the default 
      * behavior if the subclass does not define its own modifyStress
      * implementation.
      * 
      * \param paramId  index of the lattice parameter with this stress
      * \param stress  unmodified stress value
      */
      virtual double modifyStress(int paramId, double stress) const;

   };

   // Inline member functions

   // Constructor
   inline Environment::Environment()
   {  setClassName("Environment"); }

   // Destructor
   inline Environment::~Environment()
   {}

   // Return the Environment's contribution to the stress. 
   inline double Environment::stress(int paramId) const
   {  UTIL_THROW("Unimplemented stress() method called."); }

   // Modify stress to minimize a property other than fHelmholtz. 
   inline double 
   Environment::modifyStress(int paramId, double stress) const
   {  return stress; }

} // namespace Pscf
#endif