#!/usr/bin/env python3

from pscfpp.field import *

f = Field('in/w.bf')

print('Field type =' + str(f.type))

print('cell_param = ' + str(f.header['cell_param']))
print('N_basis    = ' + str(f.header['N_basis']))
print('len(data)  = ' + str(len(f.data)))

print('Setting cell_param value to 3.55')
f.header['cell_param'] = [3.55]

print(f.header)

