#!/usr/bin/env python3

from pscfpp.output import *

s = Sweep('sweep/')

report = s.summaryString(['param.Interaction.chi[0][1]','thermo.fHelmholtz'])
print(report)

array = s.summary(['param.Interaction.chi[0][1]','thermo.fHelmholtz'])
print(array)

