#!/usr/bin/env python

import sys
from pscfpp.makeDepend import *

source = sys.argv[-1]
options = ''
alldeps = ''
blddir = ''
srcdir = ''
for arg in sys.argv[1:-1]:
   if arg[:2] == '-A':
      alldeps += ' ' + arg[2:]   
   elif arg[:2] == '-B':
      blddir += arg[2:]   
   elif arg[:2] == '-S':
      srcdir += arg[2:]   
   else:
      options += ' ' + arg
options += ' -MM -MF '
processor = 'g++'

makeDepend(processor, options, source, srcdir, blddir, alldeps)
