#!/usr/bin/env python3

import sys
from pscfpp.make import *

processor = 'g++ -MM -MF'
source = sys.argv[-1]
options = ''
alldeps = ''
blddir = ''
srcdir = ''
for arg in sys.argv[1:-1]:
   if arg[:2] == '-A':
      alldeps += ' ' + arg[2:]   
   elif arg[:2] == '-B':
      blddir += arg[2:]   
   elif arg[:2] == '-S':
      srcdir += arg[2:]   
   else:
      options += ' ' + arg

createDependencyFileCpp(processor, options, source, srcdir, blddir, alldeps)
