# ==============================================================================
.PHONY: html clean

html:    
	doxygen Doxyfile

html-graphs:
	doxygen Doxyfile_allgraphs

clean:
	-rm -fr html/*


# ==============================================================================
