# ==============================================================================
.PHONY: all html clean

all:    html

html:    
	doxygen Doxyfile_html

dev:    
	doxygen Doxyfile_dev

clean:
	-rm -fr html/* 

# ==============================================================================
