#!/usr/bin/env python

from readLabel import *
file = open('test', 'r')
print readLabelledLine(file, 'variable')
print readLabelledLine(file, 'line')
print readLabelledList(file, 'list')
print readLabelledList(file, 'list')
