#!/usr/bin/env python

from ParamComposite import *

p = readParamFile('in/McSimulation')

print p
print p.FileMaster.inputPrefix
print p.SpeciesManager

print str(p.SpeciesManager.Diblock)
print str(p.SpeciesManager.Diblock[0])
print str(p.SpeciesManager.Diblock[1])
print str(p.SpeciesManager.Diblock[2])

#print p.AnalyzerManager.VanHove

